file_format: "1"
id: FrostOrtho
name: FrostOrtho
type: shield
url: https://github.com/imo00o/zmk-config-FrostOrtho
requires: [seeed_xiao]
features:
  - keys
siblings:
  - FrostOrtho_L
  - FrostOrtho_R