name: Build ZMK Firmware

on:
  push:
    paths:
      - 'config/**'
      - 'build.yaml'
      - 'zephyr/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'config/**'
      - 'build.yaml'
      - 'zephyr/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache_name: cache-west-modules
        with:
          path: |
            zmk
            zephyr
            modules
            dependencies
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-

      - name: Init
        shell: bash
        run: |
          set -eux
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          west init -l config
          west update --narrow
          west zephyr-export

      - name: Build FrostOrtho_R
        shell: bash
        run: |
          set -eux
          west build \
            -s zmk/app \
            -d build/FrostOrtho_R \
            -b xiao_ble//zmk \
            -p always \
            -S studio-rpc-usb-uart \
            -- \
            -DSHIELD=FrostOrtho_R \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Build FrostOrtho_L
        shell: bash
        run: |
          set -eux
          west build \
            -s zmk/app \
            -d build/FrostOrtho_L \
            -b xiao_ble//zmk \
            -p always \
            -- \
            -DSHIELD=FrostOrtho_L \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Build settings_reset
        shell: bash
        run: |
          set -eux
          west build \
            -s zmk/app \
            -d build/settings_reset \
            -b xiao_ble//zmk \
            -p always \
            -- \
            -DSHIELD=settings_reset \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Copy artifacts
        shell: bash
        run: |
          set -eux
          mkdir -p artifacts
          cp build/FrostOrtho_R/zephyr/zmk.uf2 artifacts/FrostOrtho_R.uf2
          cp build/FrostOrtho_L/zephyr/zmk.uf2 artifacts/FrostOrtho_L.uf2
          cp build/settings_reset/zephyr/zmk.uf2 artifacts/settings_reset.uf2

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts